//
// Generated file, do not edit! Created by nedtool 5.6 from node/OpticalMsg.msg.
//

#ifndef __OPTICALMSG_M_H
#define __OPTICALMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class OpticalMsg;
/**
 * Class generated from <tt>node/OpticalMsg.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet OpticalMsg
 * {
 *     int srcAddr;
 *     int destAddr;
 *     int slotReq;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class OpticalMsg : public ::omnetpp::cPacket
{
  protected:
    int srcAddr = 0;
    int destAddr = 0;
    int slotReq = 0;
    int hopCount = 0;

  private:
    void copy(const OpticalMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OpticalMsg&);

  public:
    OpticalMsg(const char *name=nullptr, short kind=0);
    OpticalMsg(const OpticalMsg& other);
    virtual ~OpticalMsg();
    OpticalMsg& operator=(const OpticalMsg& other);
    virtual OpticalMsg *dup() const override {return new OpticalMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);
    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr);
    virtual int getSlotReq() const;
    virtual void setSlotReq(int slotReq);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OpticalMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OpticalMsg& obj) {obj.parsimUnpack(b);}

#endif // ifndef __OPTICALMSG_M_H

